# Generated by Django 3.1.3 on 2021-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210127_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
