# Generated by Django 3.1.3 on 2021-01-27 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210127_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
