# Generated by Django 3.1.3 on 2021-01-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210128_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ppic',
        ),
        migrations.AddField(
            model_name='user',
            name='ppic',
            field=models.ImageField(blank=True, default='gallery/default.jpg', upload_to='gallery'),
        ),
    ]
