# Generated by Django 3.1.3 on 2021-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210128_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='totattime',
            field=models.IntegerField(default=0),
        ),
    ]
