# Generated by Django 3.1.3 on 2021-01-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_totattime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='totattime',
            new_name='totaltime',
        ),
    ]
