# Generated by Django 3.1.5 on 2021-02-04 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210131_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizzestaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointseanred', models.IntegerField(default=0)),
                ('quiztaken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiztaken', to='quiz.quiz')),
                ('takenby', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
