# Generated by Django 3.1.5 on 2021-02-04 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_quizzestaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzestaken',
            name='takenby',
        ),
        migrations.AddField(
            model_name='quizzestaken',
            name='takenby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takenquizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
